config/routes.rb
Rails.application.routes.draw do
  get "top/index"
  root "top#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    sessions: "users/sessions",
    confirmations: "users/confirmations"
  }

  resources :news, only: [ :index, :show ]
  resources :products, only: [ :index, :show ]
  resources :contacts, only: [ :new, :create ] do
    collection do
      post "confirm"
      get "complete"
    end
  end
  get "terms_of_use",   to: "top#terms_of_use",   as: :terms_of_use
  get "privacy_policy", to: "top#privacy_policy", as: :privacy_policy

  namespace :admin do
    root "top#index"
    devise_for :managers, controllers: {
        sessions:       "admin/managers/sessions",
        registrations:  "admin/managers/registrations"
    }
    resources :news
    resources :first_categories do
      collection do
        get  :csv_upload
        post :csv_import
      end
    end
    resources :second_categories do
      collection do
        get  :csv_upload
        post :csv_import
      end
    end
    resources :tags do
      collection do
        get  :csv_upload
        post :csv_import
      end
    end
    resources :products do
      collection do
        delete :bulk_destroy
      end
    end
    resources :media
    resources :contacts, only: [ :index, :show, :update ] do
      collection do
        get :csv_export
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/news.rb
class News < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: NewsConstants::TITLE_LENGTH_MIN, maximum: NewsConstants::TITLE_LENGTH_MAX, allow_blank: true }
  validates :link_flg,
    presence: true,
    inclusion: { in: NewsConstants::LINK_FLG_LIST.keys, allow_blank: true }
  validates :release_date,
    presence: true,
    timeliness: {
      type: :date,
      on_or_after: Date.new(2023, 1, 1),
      on_or_before: Date.new(2037, 12, 31),
      allow_blank: true
    }
  validates :release_flg,
    presence: true,
    inclusion: { in: NewsConstants::RELEASE_FLG_LIST.keys, allow_blank: true }
  validates :url,
    presence: true,
    length: { maximum: NewsConstants::URL_LENGTH_MAX, allow_blank: true },
    if: -> { link_flg == NewsConstants::LINK_FLG_ON && errors[:link_flg].blank? }
  # link_flg が false かつ、link_flg にエラーがないときのみ overview をバリデート
  validates :overview,
    presence: true,
    length: { maximum: NewsConstants::OVERVIEW_LENGTH_MAX, allow_blank: true },
    if: -> { link_flg == NewsConstants::LINK_FLG_OFF && errors[:link_flg].blank? }

  scope :released, -> {
    where(release_flg: NewsConstants::RELEASE_FLG_ON)
      .where("release_date <= ?", Date.today)
      .order(release_date: :desc, id: :desc)
  }

  scope :top_news, -> {
    where("release_date <= ?", Date.today)
      .where(release_flg: NewsConstants::RELEASE_FLG_ON)
      .order(release_date: :desc, id: :desc)
      .limit(NewsConstants::TOP_LIST_LIMIT)
  }

  def self.ransackable_attributes(auth_object = nil)
     %w[title link_flg release_date release_flg]
  end

  def self.ransackable_associations(auth_object = nil)
     []
  end
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < Admin::ApplicationController
  before_action :set_news, only: %i[ show edit update destroy ]

  # GET /admin/news or /admin/news.json
  def index
    # @news = News.all
    @q = News.ransack(params[:q])
    @news = @q.result.page(params[:page]).order(release_date: :desc, id: :desc).per(NewsConstants::ADMIN_PAGENATE_LIST_LIMIT)
  end

  # GET /admin/news/1 or /admin/news/1.json
  def show
  end

  # GET /admin/news/new
  def new
    @news = News.new
  end

  # GET /admin/news/1/edit
  def edit
  end

  # POST /admin/news or /admin/news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to [ :admin, @news ], notice: t("flash.actions.create.success", resource: News.model_name.human) }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/news/1 or /admin/news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to [ :admin, @news ], notice: t("flash.actions.update.success", resource: News.model_name.human) }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/news/1 or /admin/news/1.json
  def destroy
    @news.destroy!

    respond_to do |format|
      format.html { redirect_to admin_news_index_path, status: :see_other, notice: t("flash.actions.destroy.success", resource: News.model_name.human) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.expect(news: [ :title, :link_flg, :url, :overview, :release_date, :release_flg ])
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show ]

  def index
    @news = News.released.page(params[:page]).per(NewsConstants::PAGENATE_LIST_LIMIT)
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.released.find(params[:id])
    end
end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/index.html.erb
<% content_for :title, "お知らせ一覧" %>
<nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><%= link_to "TOP", root_path %></li>
        <li class="breadcrumb-item active" aria-current="page">お知らせ一覧</li>
    </ol>
</nav>

<div class="card shadow mb-4">
    <div class="card-body">
    <% @news.each do |news| %>
        <p class="mb-1"><%= news.release_date.strftime('%Y年%m月%d日') %></p>
        <p class="ms-4 mb-4">
        <% if news.link_flg == NewsConstants::LINK_FLG_ON %>
            <a href="<%= news.url %>" target="_blank" rel="noopener noreferrer">
                <%= news.title %>
                <%= render "shared/blank" %>
            </a>
        <% else %>
            <%= link_to news.title, news_path(news) %>
        <% end %>
        </p>
    <% end %>
    </div>
    <div class="card-footer">
        <%= paginate @news, theme: "bootstrap-5" %>
    </div>
</div>

app/views/news/show.html.erb
<% content_for :title, "お知らせ詳細" %>
<nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><%= link_to "TOP", admin_root_path %></li>
        <li class="breadcrumb-item"><%= link_to "お知らせ一覧", news_index_path %></li>
        <li class="breadcrumb-item active" aria-current="page">お知らせ詳細</li>
    </ol>
</nav>

<div class="card shadow mb-4">
    <div class="card-header"><h5 class="my-2"><%= @news.title %></h5></div>
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <span><%= simple_format(h(@news.overview)) %></span>
            </li>
        </ul>
    </div>
</div>