config/routes.rb
Rails.application.routes.draw do
  get "top/index"
  root "top#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    sessions: "users/sessions",
    confirmations: "users/confirmations"
  }

  resources :news, only: [ :index, :show ]
  resources :products, only: [ :index, :show ]
  resources :contacts, only: [ :new, :create ] do
    collection do
      post "confirm"
      get "complete"
    end
  end
  get "terms_of_use",   to: "top#terms_of_use",   as: :terms_of_use
  get "privacy_policy", to: "top#privacy_policy", as: :privacy_policy

  namespace :admin do
    root "top#index"
    devise_for :managers, controllers: {
        sessions:       "admin/managers/sessions",
        registrations:  "admin/managers/registrations"
    }
    resources :news
    resources :first_categories do
      collection do
        get  :csv_upload
        post :csv_import
      end
    end
    resources :second_categories do
      collection do
        get  :csv_upload
        post :csv_import
      end
    end
    resources :tags do
      collection do
        get  :csv_upload
        post :csv_import
      end
    end
    resources :products do
      collection do
        delete :bulk_destroy
      end
    end
    resources :media
    resources :contacts, only: [ :index, :show, :update ] do
      collection do
        get :csv_export
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :product_tags, dependent: :restrict_with_error
  has_many :products, through: :product_tags

  validates :name,
    presence: true,
    length: { maximum: TagConstants::NAME_LENGTH_MAX, allow_blank: true },
    uniqueness: { allow_blank: true }

  def self.ransackable_attributes(auth_object = nil)
     %w[name]
  end

  def self.ransackable_associations(auth_object = nil)
     []
  end
end

app/controllers/admin/tags_controller.rb
require "csv"

class Admin::TagsController < Admin::ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /admin/tags or /admin/tags.json
  def index
    # @tags = Tag.all
    @q = Tag.ransack(params[:q])
    @tags = @q.result.page(params[:page]).per(TagConstants::ADMIN_PAGENATE_LIST_LIMIT)
  end

  # GET /admin/tags/1 or /admin/tags/1.json
  def show
  end

  # GET /admin/tags/new
  def new
    @tag = Tag.new
  end

  # GET /admin/tags/1/edit
  def edit
  end

  # POST /admin/tags or /admin/tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to [ :admin, @tag ], notice: t("flash.actions.create.success", resource: Tag.model_name.human) }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/tags/1 or /admin/tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to [ :admin, @tag ], notice: t("flash.actions.update.success", resource: Tag.model_name.human) }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/tags/1 or /admin/tags/1.json
  def destroy
    if @tag.products.exists?
      redirect_to admin_tag_path(@tag), alert: "製品情報が紐づいているため削除できません。"
    else
      @tag.destroy!

      respond_to do |format|
        format.html { redirect_to admin_tags_path, status: :see_other, notice: t("flash.actions.destroy.success", resource: Tag.model_name.human) }
        format.json { head :no_content }
      end
    end
  end

  def csv_upload
  end

  def csv_import
    uploaded_file = params[:csv_file]
    if uploaded_file.blank?
      redirect_to csv_upload_admin_tags_path, alert: "CSVファイルを選択してください" and return
    end

    invalid_rows  = []
    valid_records = []
    names_seen = Set.new

    begin
      # --- 検証フェーズ ---
      CSV.foreach(uploaded_file.tempfile.path, headers: true, encoding: "SJIS:UTF-8").with_index(2) do |row, line|
        name = row["タグ名"].to_s.strip
        # ファイル内で重複している場合はエラー扱い
        if names_seen.include?(name)
          invalid_rows << { line: line, errors: "CSVファイル内で重複しているタグ名があります" }
        end

        names_seen.add(name)

        record = Tag.new(name: name)
        if record.valid?
          valid_records << record
        else
          invalid_rows << { line: line, errors: record.errors.full_messages.first }
        end
      end
    rescue Encoding::UndefinedConversionError, Encoding::InvalidByteSequenceError => _
      # 文字コードが違う場合のエラーをキャッチ
      redirect_to csv_upload_admin_tags_path, alert: "CSVファイルの文字コードがシフトJISではありません" and return
    end

    if invalid_rows.any?
      # エラーがあれば再表示
      flash.now[:alert] = "エラーがあります。修正して再アップロードしてください"
      @errors = invalid_rows
      render :csv_upload and return
    end

    # --- バルクINSERT ---
    Tag.import valid_records   # activerecord-import
    redirect_to admin_tags_path, notice: "タグを#{valid_records.size}件登録しました"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.expect(tag: [ :name ])
    end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/_form.html.erb
<%= form_with(model: [:admin, tag]) do |form| %>
<%
=begin %>
<% if tag.errors.any? %>
<div style="color: red">
    <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

    <ul>
        <% tag.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>
<% 
=end %>
<div class="card-header">
    <% if tag.new_record? %>
    タグ登録
    <% else %>
    タグ編集
    <% end %>
</div>
<div class="card-body">
    <div class="row g-3">
        <div class="col-md-12">
            <%= render 'shared/form_label', form: form, attribute: :name, label: "タグ名", required: true %>
            <%= form.text_field :name, class: "shadow-sm form-control#{' is-invalid' if form.object.errors[:name].any?}" %>
            <%= render 'shared/error_message', form: form, attribute: :name %>
        </div>
    </div>
</div>
<div class="card-footer">
    <div class="row">
        <div class="col-12 text-center my-2">
            <%= form.submit "保存", class: "btn btn-primary w-50" %>
            <%= link_to "戻る", admin_root_path, class: "btn btn-secondary", role: "button" %>
        </div>
    </div>
</div>

<% end %>

app/views/admin/tags/_index_form.html.erb
<%= search_form_for @q, url: admin_tags_path, method: :get do |form| %>

<div class="card-header">タグ一覧</div>
<div class="card-body">
    <div class="row g-3">

        <div class="col-md-12">
            <%= render 'shared/form_label', form: form, attribute: :name, label: "タグ名" %>
            <%= form.text_field :name_cont, class: "shadow-sm form-control" %>
        </div>

    </div>
</div>
<div class="card-footer">
    <div class="row">
        <div class="col-12 text-center my-2">
            <%= form.submit "検索", class: "btn btn-primary w-50" %>
            <%= link_to "戻る", admin_root_path, class: "btn btn-secondary", role: "button" %>
        </div>
    </div>
</div>
<% end %>

app/views/admin/tags/_index_tag.html.erb
<tr>
    <td scope="rol">
        <%= link_to tag.name, [:admin, tag] %>
    </td>
</tr>

app/views/admin/tags/_tag.html.erb
<div class="card-header">タグ詳細</div>
<div class="card-body">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <h5>タグ名</h5>
            <span><%= tag.name %></span>
        </li>
    </ul>
</div>
<div class="card-footer">
    <div class="row">
        <div class="col-12 text-center my-2">
            <%= link_to "編集", edit_admin_tag_path(tag), class: "btn btn-primary w-50", role: "button" %>
            <%= link_to "戻る", admin_tags_path, class: "btn btn-secondary", role: "button" %>
            <!-- Button trigger modal -->
            <% unless tag.products.exists? %>
            <button type="button" class="btn btn-outline-danger float-end" data-bs-toggle="modal" data-bs-target="#destroyModal">削除</button>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/tags/csv_upload.html.erb
<% content_for :title, "タグCSV登録" %>
<nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><%= link_to "TOP", admin_root_path %></li>
        <li class="breadcrumb-item active" aria-current="page">タグCSV登録</li>
    </ol>
</nav>

<div class="card shadow mb-4">
    <%= form_with url: csv_import_admin_tags_path, local: true, multipart: true do |f| %>
        <div class="card-header">タグCSV登録</div>
        <div class="card-body">
            <div class="row g-3">
                <div class="col-md-12">
                    <label>
                        <%= link_to "CSVテンプレートをダウンロード", "/format/tag.csv", download: "タグCSV登録フォーマット.csv" %>
                    </label>
                </div>
                <div class="col-md-12">
                    <%= render 'shared/form_label', form: f, attribute: :csv_file, label: "CSVファイル（シフトJIS）", required: true %>
                    <%= f.file_field :csv_file, accept: ".csv", class: "form-control" %>
                    <% if @errors.present? %>
                    <ul>
                        <% @errors.each do |err| %>
                        <li style="color: red"><%= err[:line] %> 行目: <%= err[:errors] %></li>
                        <% end %>
                    </ul>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-12 text-center my-2">
                    <%= f.submit "インポート", class: "btn btn-primary w-50" %>
                    <%= link_to "戻る", admin_root_path, class: "btn btn-secondary", role: "button" %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/admin/tags/edit.html.erb
<% content_for :title, "タグ編集" %>
<nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><%= link_to "TOP", admin_root_path %></li>
        <li class="breadcrumb-item"><%= link_to "タグ一覧", admin_tags_path %></li>
        <li class="breadcrumb-item"><%= link_to "タグ詳細", admin_tag_path(@tag) %></li>
        <li class="breadcrumb-item active" aria-current="page">タグ編集</li>
    </ol>
</nav>

<div class="card shadow mb-4">
    <%= render "form", tag: @tag %>
</div>

app/views/admin/tags/index.html.erb
<% content_for :title, "タグ一覧" %>

<nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><%= link_to "TOP", admin_root_path %></li>
        <li class="breadcrumb-item active" aria-current="page">タグ一覧</li>
    </ol>
</nav>

<div class="card shadow mb-4">
    <%= render "index_form" %>
</div>

<div class="card shadow mb-4">
    <div class="card-header text-end">
        <%= render 'kaminari/bootstrap-5/number', collection: @tags %>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">タグ名</th>
                </tr>
            </thead>
            <tbody>
                <% @tags.each do |tag| %>
                <%= render "index_tag", tag: tag %>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <%= paginate @tags, theme: "bootstrap-5" %>
    </div>
</div>

app/views/admin/tags/new.html.erb
<% content_for :title, "タグ登録" %>
<nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><%= link_to "TOP", admin_root_path %></li>
        <li class="breadcrumb-item active" aria-current="page">タグ登録</li>
    </ol>
</nav>

<div class="card shadow mb-4">
    <%= render "form", tag: @tag %>
</div>

app/views/admin/tags/show.html.erb
<% content_for :title, "タグ詳細" %>
<nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><%= link_to "TOP", admin_root_path %></li>
        <li class="breadcrumb-item"><%= link_to "タグ一覧", admin_tags_path %></li>
        <li class="breadcrumb-item active" aria-current="page">タグ詳細</li>
    </ol>
</nav>

<div class="card shadow mb-4">
    <%= render @tag %>
</div>
<%= render "shared/destroy_modal", title: "タグ", path: admin_tag_path(@tag) %>