config/routes.rb
Rails.application.routes.draw do
  get "top/index"
  root "top#index"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    sessions: "users/sessions",
    confirmations: "users/confirmations"
  }

  resources :news, only: [ :index, :show ]
  resources :products, only: [ :index, :show ]
  resources :contacts, only: [ :new, :create ] do
    collection do
      post "confirm"
      get "complete"
    end
  end
  get "terms_of_use",   to: "top#terms_of_use",   as: :terms_of_use
  get "privacy_policy", to: "top#privacy_policy", as: :privacy_policy

  namespace :admin do
    root "top#index"
    devise_for :managers, controllers: {
        sessions:       "admin/managers/sessions",
        registrations:  "admin/managers/registrations"
    }
    resources :news
    resources :first_categories do
      collection do
        get  :csv_upload
        post :csv_import
      end
    end
    resources :second_categories do
      collection do
        get  :csv_upload
        post :csv_import
      end
    end
    resources :tags do
      collection do
        get  :csv_upload
        post :csv_import
      end
    end
    resources :products do
      collection do
        delete :bulk_destroy
      end
    end
    resources :media
    resources :contacts, only: [ :index, :show, :update ] do
      collection do
        get :csv_export
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/admin/layouts/_footer.html.erb
<footer class="my-1 pt-4 text-muted text-center text-small">
    <p class="mb-1">&copy; 2025− へろっちシマウマ～ず</p>
    <ul class="list-inline">
        <li class="list-inline-item">
            <%= link_to terms_of_use_path, target: "_blank", rel: "noopener noreferrer" do %>
            利用規約<%= render "shared/blank" %>
            <% end %>
        </li>
        <li class="list-inline-item">
            <%= link_to privacy_policy_path, target: "_blank", rel: "noopener noreferrer" do %>
            プライバシーポリシー<%= render "shared/blank" %>
            <% end %>
        </li>
    </ul>
</footer>

app/views/admin/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-bottom-dark mb-3" data-bs-theme="dark">
    <div class="container-fluid">
        <%= image_tag "logo.png", alt: "TOP", class: "", width: "32", height: "32" %>
        <span class="text-danger fs-4 fw-semibold ps-2">管理画面</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "TOP", admin_root_path, class: "nav-link#{" active" if controller.controller_name == "top" && action_name == "index"}" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle <%= "active" if controller.controller_name == "news" %>" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" <%= 'aria-current="page"' if controller.controller_name == "news" %>>お知らせ
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "お知らせ登録", new_admin_news_path, class: "dropdown-item#{" active" if controller.controller_name == "news" && action_name == "new"}" %></li>
                        <li><%= link_to "お知らせ一覧", admin_news_index_path, class: "dropdown-item#{" active" if controller.controller_name == "news" && action_name == "index"}" %></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle <%= "active" if controller.controller_name == "first_categories" || controller.controller_name == "second_categories" %>" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"<%= 'aria-current="page"' if controller.controller_name == "first_categories" || controller.controller_name == "second_categories" %>>カテゴリ
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "大カテゴリ登録", new_admin_first_category_path, class: "dropdown-item#{" active" if controller.controller_name == "first_categories" && action_name == "new"}" %></li>
                        <li><%= link_to "大カテゴリ一覧", admin_first_categories_path, class: "dropdown-item#{" active" if controller.controller_name == "first_categories" && action_name == "index"}" %></li>
                        <li><%= link_to "大カテゴリCSV登録", csv_upload_admin_first_categories_path, class: "dropdown-item#{" active" if controller.controller_name == "first_categories" && action_name == "csv_upload"}" %></li>
                        <li><%= link_to "中カテゴリ登録", new_admin_second_category_path, class: "dropdown-item#{" active" if controller.controller_name == "second_categories" && action_name == "new"}" %></li>
                        <li><%= link_to "中カテゴリ一覧", admin_second_categories_path, class: "dropdown-item#{" active" if controller.controller_name == "second_categories" && action_name == "index"}" %></li>
                        <li><%= link_to "中カテゴリCSV登録", csv_upload_admin_second_categories_path, class: "dropdown-item#{" active" if controller.controller_name == "second_categories" && action_name == "csv_upload"}" %></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle <%= "active" if controller.controller_name == "tags" %>" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" <%= 'aria-current="page"' if controller.controller_name == "tags" %>>タグ
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "タグ登録", new_admin_tag_path, class: "dropdown-item#{" active" if controller.controller_name == "tags" && action_name == "new"}" %></li>
                        <li><%= link_to "タグ一覧", admin_tags_path, class: "dropdown-item#{" active" if controller.controller_name == "tags" && action_name == "index"}" %></li>
                        <li><%= link_to "タグCSV登録", csv_upload_admin_tags_path, class: "dropdown-item#{" active" if controller.controller_name == "tags" && action_name == "csv_upload"}" %></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle <%= "active" if controller.controller_name == "products" %>" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" <%= 'aria-current="page"' if controller.controller_name == "products" %>>製品情報
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "製品情報登録", new_admin_product_path, class: "dropdown-item#{" active" if controller.controller_name == "products" && action_name == "new"}" %></li>
                        <li><%= link_to "製品情報一覧", admin_products_path, class: "dropdown-item#{" active" if controller.controller_name == "products" && action_name == "index"}" %></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle <%= "active" if controller.controller_name == "media" %>" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" <%= 'aria-current="page"' if controller.controller_name == "media" %>>メディア
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "メディア登録", new_admin_medium_path, class: "dropdown-item#{" active" if controller.controller_name == "media" && action_name == "new"}" %></li>
                        <li><%= link_to "メディア一覧", admin_media_path, class: "dropdown-item#{" active" if controller.controller_name == "media" && action_name == "index"}" %></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle <%= "active" if controller.controller_name == "contacts" %>" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" <%= 'aria-current="page"' if controller.controller_name == "contacts" %>>お問い合わせ
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "お問い合わせ一覧", admin_contacts_path, class: "dropdown-item#{" active" if controller.controller_name == "contacts" && action_name == "index"}" %></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <%= link_to "プロフィール", edit_admin_manager_registration_path, class: "nav-link#{" active" if controller.controller_name == "registrations" && action_name == "edit"}" %>
                </li>
            </ul>
            <%= button_to "ログアウト", destroy_admin_manager_session_path, method: :delete, class: "btn btn-outline-success" %>
        </div>
    </div>
</nav>

app/views/admin/layouts/_toasts.html.erb
<div class="toast-container position-fixed top-0 end-0 p-3">
    <% if flash[:notice] || flash[:success] %>
    <div id="successToast" class="toast align-items-center text-bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
                <%= flash[:notice] || flash[:success] %>
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
    <% elsif flash[:alert] || flash[:failure] %>
    <div id="failureToast" class="toast align-items-center text-bg-danger border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
                <%= flash[:alert] || flash[:failure] %>
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
    <% end %>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const successToast = document.getElementById('successToast');
        const failureToast = document.getElementById('failureToast');
        const option = {
            'animation': true,
            'autohide': true,
            'delay': 5000,
        };
        if (successToast) {
            const toast = new bootstrap.Toast(successToast, option);
            toast.show();
        } else if (failureToast) {
            const toast = new bootstrap.Toast(failureToast, option);
            toast.show();
        }
    });
</script>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>管理側 | <%= content_for(:title) %> | Herotchi_CMS2_Ruby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
    <%= javascript_importmap_tags %>
</head>

<body class="bg-body-tertiary h-100">
    <%= render "admin/layouts/navigation" %>
    <div class="container">
        <main>
            <%= yield %>
        </main>
        <%= render "layouts/footer" %>
        <%= render "admin/layouts/toasts" %>
    </div>
</body>

</html>

app/views/admin/layouts/guest.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>管理側 | <%= content_for(:title) %> | Herotchi_CMS2_Ruby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
    <%= javascript_importmap_tags %>
    <style>
        body {
            padding-top: 40px;
            padding-bottom: 40px;
        }

        .no-header {
            width: 100%;
            max-width: 480px;
            padding: 15px;
            margin: auto;
        }
    </style>
</head>

<body class="bg-body-tertiary h-100">
    <div class="container">
        <main>
            <div class="no-header">
                <div class="text-center">
                    <%= image_tag("logo.png", alt: "Herotchi_CMS2_Ruby", class: "my-4", width: "57", height: "57") %>
                </div>
                <%= yield %>
            </div>
        </main>
        <%= render "admin/layouts/toasts" %>
    </div>
</body>

</html>